version: "1.0.{build}"
image: Visual Studio 2017
branches:
  only:
    - master
dotnet_csproj:
  patch: true
  file: "**\*.csproj"
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"
init:
  - cmd: git config --global core.autocrlf true
install:
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore --verbosity m
build_script:
  - cmd: dotnet build -c Release
  - cmd: dotnet publish ./Mixpanel/Mixpanel.csproj -c Release
after_build:
artifacts:
  - path: "./Mixpanel/bin/Release/netstandard2.0/publish"
    name: NMixpanel
clone_depth: 1
test_script:
  - cmd: dotnet test
on_finish:
deploy: off
